version: '3.7'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8888:80"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ../frontend/dist:/usr/share/nginx/html

  server:
    build:
      context: .
      dockerfile: docker/server.dockerfile
    restart: always
    ports:
      - "80:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run api
    volumes:
      - ./docker/cloudflared:/etc/cloudflared
volumes:
  mariadb_data: